# Generated by Django 4.0.6 on 2022-09-22 07:34

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import g_muso_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Membre')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codep', models.CharField(blank=True, max_length=50, verbose_name='CODE MEMBRE ')),
                ('nomp', models.CharField(blank=True, max_length=50, null=True, verbose_name='NOM MEMBRE ')),
                ('prenomp', models.CharField(blank=True, max_length=50, null=True, verbose_name='PRENOM MEMBRE ')),
                ('sexep', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE ')),
                ('lieunaissancep', models.CharField(blank=True, max_length=50, null=True, verbose_name='LIEU DE NAISSANCE ')),
                ('adressep', models.CharField(blank=True, max_length=50, null=True, verbose_name='ADRESSE ')),
                ('villep', models.CharField(blank=True, max_length=50, null=True, verbose_name='VILLE ')),
                ('communep', models.CharField(blank=True, max_length=50, null=True, verbose_name='COMMUNE ')),
                ('departementp', models.CharField(blank=True, max_length=50, null=True, verbose_name='DEPARTEMENT ')),
                ('paysp', models.CharField(blank=True, max_length=50, null=True, verbose_name='PAYS ')),
                ('nifp', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF/CIN ')),
                ('telephone1p', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE 1 ')),
                ('telephone2p', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEPHONE 2 ')),
                ('activiteprofessionp', models.CharField(blank=True, max_length=50, null=True, verbose_name='ACTIVITE / PROFESSION ')),
                ('referencep', models.CharField(blank=True, max_length=50, null=True, verbose_name='REFERENCE ')),
                ('dateajout', models.DateTimeField(auto_now=True, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=g_muso_app.models.filepath)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tbcredit',
            fields=[
                ('numero', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='Numero Credit')),
                ('date_credit', models.DateTimeField(verbose_name='Date Credit (YYYY-MM-DD)')),
                ('nbre_de_mois', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Nombre de Mois')),
                ('date_debut', models.DateTimeField(verbose_name='Date debut (YYYY-MM-DD)')),
                ('date_fin', models.DateTimeField(verbose_name='Date Fin (YYYY-MM-DD)')),
                ('montant_credit', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Montant Credit')),
                ('interet_credit', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Interet Credit')),
                ('commentaire', models.TextField()),
                ('valider_par', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valider Par')),
                ('credit_status', models.CharField(blank=True, default='En cour', max_length=50, null=True, verbose_name='Status Credit')),
                ('code_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='tbremboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_remb', models.DateField(blank=True, verbose_name='Date Remboursement (YYYY-MM-DD)')),
                ('montant_a_remb', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Montant Credit')),
                ('capital_remb', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Capital Remboursement')),
                ('interet_remb', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Interet Remboursement')),
                ('balance', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Balance')),
                ('penalite', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Penalite')),
                ('commentaire', models.TextField()),
                ('recu_par', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recu Par')),
                ('codecredit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.tbcredit')),
                ('faites_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='tbcotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecotisation', models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation')),
                ('montant', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Montant')),
                ('interet', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Interet')),
                ('balance', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Balance')),
                ('date_fait', models.DateTimeField(verbose_name='Date Cotisation (YYYY-MM-DD)')),
                ('penalite', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Penalite')),
                ('recu_par', models.CharField(blank=True, max_length=50, null=True, verbose_name='Recu Par')),
                ('code_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('code_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReportMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('code_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('code_membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.membre')),
            ],
        ),
        migrations.CreateModel(
            name='AdminHOD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
