# Generated by Django 3.2.18 on 2023-03-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0004_alter_customuser_first_name_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbdepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(blank=True, verbose_name='Date Depense (YYYY-MM-DD)')),
                ('description', models.TextField()),
                ('depense_unit', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Prix Unit')),
                ('quantite_dep', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Quantite')),
            ],
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
