# Generated by Django 3.2.18 on 2023-03-13 08:21

from django.db import migrations, models
import g_muso_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0006_auto_20230310_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbmuso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codemuso', models.CharField(blank=True, max_length=50, verbose_name='CODE MUSO ')),
                ('sigle', models.CharField(blank=True, max_length=50, verbose_name='SIGLE ')),
                ('nom_muso', models.CharField(blank=True, max_length=50, verbose_name='NOM ')),
                ('adresse_muso', models.CharField(blank=True, max_length=50, verbose_name='ADRESSE ')),
                ('telephone_muso', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('email_muso', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('site_muso', models.CharField(blank=True, max_length=50, verbose_name='TELEPHONE ')),
                ('logo_muso', models.FileField(blank=True, null=True, upload_to=g_muso_app.models.filepath)),
                ('date_creation', models.DateTimeField(verbose_name='Date Creation')),
            ],
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
