# Generated by Django 3.2.18 on 2023-03-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0007_auto_20230313_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='muso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.tbmuso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
