# Generated by Django 3.2.18 on 2023-06-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0011_auto_20230322_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds de Credit', 'Fonds de Credit'), ('Fonds Urgences', 'Fonds Urgences')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
        migrations.CreateModel(
            name='tbdetailproduit',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom Produit ')),
                ('quantite_prod', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Quantite ')),
                ('prix_unitaire', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Prix Unitaire')),
                ('prix_total', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Prix Total')),
                ('frais_transport', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Montant transporter')),
                ('prix_de_revient', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Prix de Revient')),
                ('prix_de_vente', models.FloatField(blank=True, default='0.0', null=True, verbose_name='Prix de Vente')),
                ('codecredit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.tbcredit')),
            ],
        ),
    ]
