# Generated by Django 3.2.18 on 2023-06-12 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0015_auto_20230612_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='muso_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='g_muso_app.tbmuso'),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement'), ('Fonds de Credit', 'Fonds de Credit')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
