# Generated by Django 3.2.18 on 2023-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0018_alter_membre_sexep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='sexep',
            field=models.CharField(blank=True, choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=50, null=True, verbose_name='SEXE MEMBRE '),
        ),
        migrations.AlterField(
            model_name='tbcotisation',
            name='typecotisation',
            field=models.CharField(blank=True, choices=[('Fonds Urgences', 'Fonds Urgences'), ('Fonds de Credit', 'Fonds de Credit'), ('Fonds de Fonctionnement', 'Fonds de Fonctionnement')], max_length=50, null=True, verbose_name='Type de Cotisation'),
        ),
    ]
