# Generated by Django 3.2.18 on 2023-06-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_muso_app', '0020_tbdetailproduit_unite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmuso',
            name='couleur_preferee',
            field=models.CharField(blank=True, default='#2471A3', max_length=50, verbose_name='Couleur Preferee '),
        ),
        migrations.AddField(
            model_name='tbmuso',
            name='taux_interet',
            field=models.FloatField(blank=True, default='0.0', null=True, verbose_name='Taux Interet'),
        ),
    ]
